# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 12 # it will paginate after this number
language: 'pt-br'

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
# baseurl: /jasper2/
baseurl: ""

# Website info
title: Blog.onedev.studio
description: The professional publishing platform
cover: assets/images/blog-cover.jpg
logo: assets/images/blog-icon.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
production_url: http://blog.onedev.studio/
source_url: https://github.com/onedevstudio/blog/

# Social info
navigation: true # show the navbar links
subscribers: true # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: onedevstudioweb
# facebook: oseunando

# Disqus
disqus: False
disqus_shortname: onedevstudio

# Google Analytics
google_analytics: UA-00000000-1

# Permalinks
permalink: /:title

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins:
  - jekyll-paginate
  - jekyll-feed

feed:
  path: feed.xml

exclude:
  - assets/css
  - node_modules
  - vendor
  - Gemfile
  - Gemfile_
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
