lang: 'pt_BR'
baseurl: ""
url: ""
title: Blog.onedev.studio
email: nandomoreira.me@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
image: ''
author: 'Fernando Moreira'
twitter_username: oseunando
github_username:  nandomoreirame
dribbble_username: umdevux
facebook_username: oseunando
linkedin_username: nandomoreirame

# logo: ''
social:
  name: Fernando Moreira
  links:
    - https://twitter.com/oseunando
    - https://github.com/nandomoreirame
    - https://www.linkedin.com/in/nandomoreirame
    - https://www.facebook.com/oseunando
twitter:
  username: oseunando
# google_site_verification: '123'

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docker-compose.yml
  - README.md
  - LICENSE
