# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 12
paginate_path: "/page/:num"
language: 'pt-br'

baseurl: ""

# Website info
title: Onedev.studio
description: Um estúdio digital focado em consultoria e desenvolvimento web.
cover: assets/images/blog-cover.png
logo: false
logo_dark: false
favicon: assets/images/favicon.png
production_url: https://blog.onedev.studio/

# Social info
navigation: true # show the navbar links
subscribers: false # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: onedevstudioweb
# facebook: oseunando

# Disqus
disqus: true
disqus_shortname: fernandomoreira

# Google Analytics
google_analytics: UA-119443578-1

# Permalinks
permalink: /:title

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

plugins_dir: ./_plugins

# gems and other configs
plugins:
  - jekyll-paginate
  - jekyll-feed

feed:
  path: feed.xml

compress_html:
  clippings: all
  comments:  all
  endings: all
  profile: false

exclude:
  - assets/css
  - node_modules
  - vendor
  - Gemfile
  - Gemfile_
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
